### ISSUE TITLE
Not working with <!DOCTYPE html>

### ISSUE THREAD

**Issue by leolorca** [alexfoxy/lax.js#102]
Hi dear dev:

Not working with  **< !DOCTYPE html >** declared. At least not in my test. Lastest version 2.

Thanks for the good work!!
regards

**Comment by markaba** [comment]
Hi all,
I had the same problem - found out, that it should be changed to `document.documentElement.scrollTop`
in the driver as document.body.scrollTop is deprecated.
This works!

**Comment by evwebcoder** [comment]
Oh my, I was running into this for a while, thanks for the fix @markaba

**Comment by alexfoxy** [comment]
You can just use window.scrollTop too
