### ISSUE TITLE
Lacks a feature which rellax.js offers.

### ISSUE THREAD

**Issue by imabyk** [alexfoxy/lax.js#106]
Can't make element to follow the cursor like rellax.js allows us to do...for reference see the video link given below.
https://youtu.be/dc4zyX6DuOc

**Comment by alexfoxy** [comment]
@imabyk This is do-able in lax 2.0 - I'm hoping to release it soon but it's available to try on the https://github.com/alexfoxy/lax.js/tree/version-2 branch.
