### ISSUE TITLE
Dynamically setting scroll position on variable number of elements with Vue & v-for

### ISSUE THREAD

**Issue by jzstern** [alexfoxy/lax.js#109]
Been loving lax.js - thanks for making such an awesome library!

I'm trying to use some lax transitions (starting with using opacity for a basic fade in/out) to animate one verse from a song at a time as the user scrolls. There are multiple songs with variable length, and I'm rendering them like so:
### Template
```
<div
  class="lyrics-section"
  v-for="(verse, index) in lyrics"
  :data-lax-opacity="getLaxOpacity(index)"
  :key="index"
  :ref="'lyrics'+ index"
>
   <p v-for="(line, lineIndex) in verse" :key="lineIndex">{{line}}</p>
</div>
```
### Script
```
initLaxElements(numElements) {
  for (let i = 0; i < numElements; i++) {
    let ref = "lyrics" + i ;
    this.$lax.addElement(this.$refs[ref]);
  }
}

...

mounted() {
  this.initLaxElements(this.lyrics.length);
}
```

`lyrics` is a computed value grabbing the 2D lyrics array off the `currentSong` object from my Vuex store. The inner arrays (verses) hold a list of strings (one for each line of the song)

`getLaxOpacity()` dynamically returns the scroll behavior (e.g. `"(vh*2) 0, (vh*2.5) 1, (vh*2.7) 0"`) based on the index of the lyric chunk. I've verified this method works correctly and have even tried replacing it with a static value to no avail

 The content is rendered correctly, but fails to animate and throws the following error when I try to initialize the first lax element in `initLaxElements()`

> [Vue warn]: Error in updated hook: "TypeError: Cannot read property 'transform' of undefined"
> TypeError: Cannot read property 'transform' of undefined
    at Object.lax.createLaxObject (lax.min.js?db5d:1)
    at Object.lax.addElement (lax.min.js?db5d:1)
    at VueComponent.initLaxElements (Lyrics.vue?d78b:34)
    at VueComponent.updated (Lyrics.vue?d78b:57)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at callHook (vue.runtime.esm.js?2b0e:4213)
    at callUpdatedHooks (vue.runtime.esm.js?2b0e:4345)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4330)
    at Array.eval (vue.runtime.esm.js?2b0e:1980)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1906)

I've been able to successfully animate the content if I hard code it (while calling `initLaxElements()` in `mounted()`), but I can't figure out why the v-for is breaking things. Happy to provide more details/code snippets (sorry if I didn't explain this very well).

**Comment by jzstern** [comment]
Decided to not use lax for this in the end, but happy to elaborate on the request

**Comment by arthurdenner** [comment]
@jzstern, it's easier for maintainers to understand with a reproducible example. Maybe you can create a [sandbox](https://codesandbox.io/s/vue-vue).
