### ISSUE TITLE
React Codepen example doesn't work

### ISSUE THREAD

**Issue by username1001** [alexfoxy/lax.js#110]
Just a blank page on both Firefox and Chromium

**Comment by goodbreathseth** [comment]
The Vue example doesn't work either... It isn't blank, but it doesn't reflect any lax animations

**Comment by arthurdenner** [comment]
The reason is that the URL for the library has changed to `https://alexfox.dev/lax.js/lib/lax.min.js`.

I've forked and fixed both examples:

React: https://codepen.io/arthurdenner/pen/jOqwaQw
Vue: https://codepen.io/arthurdenner/pen/mdPwqay

**Comment by username1001** [comment]
Awesome, thanks, @arthurdenner! :smile:
