### ISSUE TITLE
Momentum - Max value (Version 2)

### ISSUE THREAD

**Issue by robizzt** [alexfoxy/lax.js#111]
Hello.

I was wondering is there an option to set max value on momentum?

In your example (https://codesandbox.io/embed/lax-examples-momentum-tisoc?fontsize=14&hidenavigation=1&theme=dark&view=preview), if you grab scrollbar thumb, and drag it fast from top to bottom, you should notice that square will filp few times before going back to its original position.

So if I could place, let's say, limit on how many deg square will rotate on X axis, that would be great.

Everything else works perfectly, regarding Momentum.

**Comment by alexfoxy** [comment]
Interesting find, I suppose I could limit the momentum to a reasonable value.

**Comment by robizzt** [comment]
Or add an option where you can limit momentum to desired value.

**Comment by alexfoxy** [comment]
Hey, following the release of Lax 2.0 I am now marking this as a todo and will add it in a future update.

**Comment by alexfoxy** [comment]
I tried adding a max value but the result wasn't very visually satisfying. For now I am closing this ticket.
