### ISSUE TITLE
Breakpoint documentation not clear

### ISSUE THREAD

**Issue by welbinator** [alexfoxy/lax.js#114]
I added 

`breakpoints: { small: 500, medium: 680 }`

and then added _medium to the end of my lax data sets like so:

`data-lax-translate-x_medium="vh 0, -elh (vw*0.8)"`

All it did was reverse the animation. It moves left now instead of right. 

All I want to do is disable the scroll animation on screens < 500px.

**Comment by alexfoxy** [comment]
Hey, following the release of Lax 2.0 I am now closing this issue as it should be resolved.
