### ISSUE TITLE
data attributes not working with <span>?

### ISSUE THREAD

**Issue by ma66ot87** [alexfoxy/lax.js#116]
I tried to use a data-lax-scale within a span tag but it doesn't work. data-lax-presets is working fine though. What am I doing wrong?

This is my code:

    <span class="lax" data-lax-preset="fadeOut">THIS IS <br>MY</span> <span class="lax" data-lax-scale="50 20, 200  1" data-lax-anchor="self">PORTFOLIO</span>

**Comment by alexfoxy** [comment]
Hey, following the release of Lax 2.0 I am now closing this issue as it should be resolved.
