### ISSUE TITLE
lax not loading on firefox on some pages

### ISSUE THREAD

**Issue by hocomadvies** [alexfoxy/lax.js#117]
Hi, I experience a problem in Firefox and now also on Safari mobile version (iPhone). The items on the page with lax applied are not loading on some pages. Here is the live design-example of the dev- site: http://dev10.shufflemix.nl/toepassingen/glazuur

Also on the nl home-page the big white area's with the button under are not loading (should be 6 tiles with images). Or some-times only once and than after visiting an other page they are not loading again? What is wrong here? 

Would it be possible having an setting which make sure that the images are always loaded?

this is in my html al very basic and standard:

<div class="lax" data-lax-preset="zoomIn fadeIn "></>

also tried to add <div class="lax" data-lax-preset="zoomIn fadeIn speed=2"> which seems not helping. 

On the pages I have lax  there is also an Slick.js could that be interfering? 

How to get this right? Please advise I need to fix this or look for a other solution.

**Comment by hocomadvies** [comment]
This is the error message which is generated in Firefox:

`This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! `

Might that be the reason the lax.js is not working properly?

**Comment by alexfoxy** [comment]
Hey, following the release of Lax 2.0 I am now closing this issue as it should be resolved.

**Comment by alexfoxy** [comment]
Hey @hocomadvies please try the new lax 2.0 to see if this is still an issue.

**Comment by hocomadvies** [comment]
OK will have a look at that.
