### ISSUE TITLE
data-lax-anchor

### ISSUE THREAD

**Issue by AirMaks** [alexfoxy/lax.js#118]
Previous lax version had data-lax-anchor option, is there a way to bind element (data-lax-anchor="#anchor") in the new version?

**Comment by alexfoxy** [comment]
Currently there are only the special values which can be used: https://github.com/alexfoxy/lax.js#special-values

What is your particular use case?

**Comment by alexfoxy** [comment]
@AirMaks Please re-open when you have some more info.

**Comment by AirMaks** [comment]
Yep, thanks, elCenterY solves my issue : )
