### ISSUE TITLE
getValueFn doesn't receive frame as argument

### ISSUE THREAD

**Issue by arthurdenner** [alexfoxy/lax.js#123]
**lax.js version**
2.0.2

**Describe the bug**
The docs state that `getValueFn` receives the `frame` as an argument but [that's not implemented](https://github.com/alexfoxy/lax.js/blob/master/src/lax.js#L331).

Are the docs not up-to-date or should the code be updated?

**Code**
N/A

**Comment by alexfoxy** [comment]
I will check it out

**Comment by alexfoxy** [comment]
@arthurdenner Fixed in v2.0.3 => https://github.com/alexfoxy/lax.js/releases/tag/v2.0.3

**Comment by arthurdenner** [comment]
Thanks @alexfoxy! I'll wrap up the v2 of `use-lax` very soon then!
