### ISSUE TITLE
Deprecate eval()

### ISSUE THREAD

**Issue by clarknelson** [alexfoxy/lax.js#125]
**Is your feature request related to a problem? Please describe.**
I am writing a content security policy for my website, and Lax seems to use the JS `eval()`. 

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'nonce-...'".
```

**Describe the solution you'd like**
Can we somehow remove the eval call from the framework?

**Describe alternatives you've considered**
I've tried V1 with this stack trace:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'nonce-...'".

    at fnOrVal (vendor.min.js?stamp=10302020:20508)
    at Array.map (<anonymous>)
    at vendor.min.js?stamp=10302020:20508
    at Array.map (<anonymous>)
    at vendor.min.js?stamp=10302020:20508
    at Object.lax.calcTransforms (vendor.min.js?stamp=10302020:20508)
    at lax.addElement (vendor.min.js?stamp=10302020:20508)
    at NodeList.forEach (<anonymous>)
    at Object.lax.populateElements (vendor.min.js?stamp=10302020:20508)
    at Object.lax.setup (vendor.min.js?stamp=10302020:20508)
```

And V2 with this stack trace:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'nonce-...'".

    at Function (<anonymous>)
    at d (vendor.min.js?stamp=1609172397:20508)
    at vendor.min.js?stamp=1609172397:20508
    at Array.map (<anonymous>)
    at vendor.min.js?stamp=1609172397:20508
    at vendor.min.js?stamp=1609172397:20508
    at f.calculateTransforms (vendor.min.js?stamp=1609172397:20508)
    at new f (vendor.min.js?stamp=1609172397:20508)
    at vendor.min.js?stamp=1609172397:20508
    at NodeList.forEach (<anonymous>)
```

**Additional context**
I don't know very much about eval...

**Comment by alexfoxy** [comment]
That's odd, I removed eval from v2 so I'm not sure if babel is compiling it to use eval. I will look into it.

**Comment by clarknelson** [comment]
thank you! I will try to clear my caches

**Comment by clarknelson** [comment]
removed node_modules and rebuilt my script files, but still have same message. glad to hear you may be able to resolve this though! thank you for the wonderful animation framework

**Comment by alexfoxy** [comment]
@clarknelson I've just had a dig through the compiled source and lax.js v2 doesn't use unsafe-eval. Perhaps you're still using v1 which did use eval?

**Comment by clarknelson** [comment]
Maybe this is the issue?

/src/lax.js:270-302
```
    function parseValue(val, { width, height, x, y }, index) {
      if (typeof val === 'number') {
        return val
      }

      const pageHeight = document.body.scrollHeight
      const pageWidth = document.body.scrollWidth
      const screenWidth = window.innerWidth
      const screenHeight = window.innerHeight
      const scrollTop = window.scrollY
      const scrollLeft = window.scrollX

      const left = x + scrollLeft
      const right = left + width
      const top = y + scrollTop
      const bottom = top + height

      return Function(`return ${val
        .replace(/screenWidth/g, screenWidth)
        .replace(/screenHeight/g, screenHeight)
        .replace(/pageHeight/g, pageHeight)
        .replace(/pageWidth/g, pageWidth)
        .replace(/elWidth/g, width)
        .replace(/elHeight/g, height)
        .replace(/elInY/g, top - screenHeight)
        .replace(/elOutY/g, bottom)
        .replace(/elCenterY/g, top + (height / 2) - (screenHeight / 2))
        .replace(/elInX/g, left - screenWidth)
        .replace(/elOutX/g, right)
        .replace(/elCenterX/g, left + (width / 2) - (screenWidth / 2))
        .replace(/index/g, index)
        }`)()
    }
```

Looks like line 287 is using `Function`?

**Comment by clarknelson** [comment]
I believe `eval()` and `new Function` are similar enough to throw this error x.x 

I'm not an expert here, but would `()=>{}` or `function(){}` have a similar result to `new Function()`?

**Comment by alexfoxy** [comment]
Perhaps. Unfortunately this is integral to the how the library works right now. The only way round it would be to write some custom parse for the formula. For now perhaps you can try different header policy as documented here: https://github.com/exceljs/exceljs/issues/713 ?

**Comment by clarknelson** [comment]
would something like this work?

```
      const calcValue = function(){
        `return ${val
          .replace(/screenWidth/g, screenWidth)
          .replace(/screenHeight/g, screenHeight)
          .replace(/pageHeight/g, pageHeight)
          .replace(/pageWidth/g, pageWidth)
          .replace(/elWidth/g, width)
          .replace(/elHeight/g, height)
          .replace(/elInY/g, top - screenHeight)
          .replace(/elOutY/g, bottom)
          .replace(/elCenterY/g, top + (height / 2) - (screenHeight / 2))
          .replace(/elInX/g, left - screenWidth)
          .replace(/elOutX/g, right)
          .replace(/elCenterX/g, left + (width / 2) - (screenWidth / 2))
          .replace(/index/g, index)
          }`
      }
      return calcValue();
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Function

**Comment by alexfoxy** [comment]
The issue is that the string needs to be evaluated as javascript, so I'm afraid that won't work.

**Comment by clarknelson** [comment]
okay thank you, I am curious how `Function(x)()` is actually executing anything to be honest! I had thought that the tildes would be executing the JS. 

I'll probably have to move on to a custom implementation, but I will keep lax in mind for website with less asinine security policies.

**Comment by alexfoxy** [comment]
It essentially parses the string as javascript e.g; 
<img width="215" alt="Screenshot 2020-12-28 at 19 04 32" src="https://user-images.githubusercontent.com/151772/103237457-94042900-493f-11eb-8f80-7b0127e46b53.png">

Sorry I couldn't solve it for you!

**Comment by clarknelson** [comment]
No problem, thank you for the help :)
