### ISSUE TITLE
Avoid the effect of intermittent animation when using regular mouse-wheels

### ISSUE THREAD

**Issue by jt3k** [alexfoxy/lax.js#71]
Hi! In the readme file, I read the following:

- [ ] Implement a tween for scroll wheels to remove reliance on smoothscroll
288

If I understand you correctly, you need to avoid the effect of intermittent animation when using regular mouse-wheels (not Apple-magic-mouse or touchpad).

I think I can help do this in a demo example, and then we can add this to the api as an option

**Comment by alexfoxy** [comment]
Hey!

Yes exactly. I think there needs to be an option for an easing as requested in #59 

There's a demo here: https://codepen.io/drozumek/pen/qBBKxGg

Do you have another idea?

**Comment by jt3k** [comment]
I wanted to offer a more flexible solution. Based on this example https://stackoverflow.com/q/47011055

Of course, we have to reconsider the vendor methods and the use of setTimeout but generally works well.

look here:
https://jt3k.github.io/laxxx
https://jt3k.github.io/laxxx/sprite

**Comment by alexfoxy** [comment]
Yeah, I think I used smooth scroll before. I am concerned about performance however. I need to do a few tests before committing to a path.

**Comment by jt3k** [comment]
I'm using now
```css
.lax {transition: transform .5s;}
```
I think this is the best way to achieve the same, and avoid performance issue.

**Comment by SGarcia710** [comment]
> I wanted to offer a more flexible solution. Based on this example https://stackoverflow.com/a/47206289/2378829
> 
> Of course, we have to reconsider the vendor prefixes and the use of setTimeout,
> but it seems to work well
> 
> look here:
> https://jt3k.github.io/laxxx
> https://jt3k.github.io/laxxx/sprite

Excuse me sir, can you share the repos for these solutions you have made? I am dealing with the same issue and the 
```css
.lax {transition: transform .5s;}
```
is not a good solution for my needs.

**Comment by SGarcia710** [comment]
> I wanted to offer a more flexible solution. Based on this example https://stackoverflow.com/a/47206289/2378829
> 
> Of course, we have to reconsider the vendor prefixes and the use of setTimeout,
> but it seems to work well
> 
> look here:
> https://jt3k.github.io/laxxx
> https://jt3k.github.io/laxxx/sprite

Excuse me sir, can you share the repos for these solutions you have made? I am dealing with the same issue and the 
```css
.lax {transition: transform .5s;}
```
is not a good solution for my needs.

**Comment by alexfoxy** [comment]
I am closing this as I think the solution @jt3k provided should be addequate.
