### ISSUE TITLE
npm package page SEO

### ISSUE THREAD

**Issue by mauriciabad** [alexfoxy/lax.js#89]
I noticed that if you search `lax.js npm` the npm package page doesn't show up, instead another random package appears. This confused me for a while trying to install it through npm because I didn't look at the readme. 

I suggest adding some keywords, specially: `laxxx`, `lax`, `lax.js`, `laxjs`, `laxxxjs`.
And also adding the npm package url somewhere in the readme (for example in the NPM Setup section). 

Search result:
![CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US-000207](https://user-images.githubusercontent.com/12821361/77966491-6f611f00-72e3-11ea-9b8a-c9f4c7c9e52e.png)

btw, i love this package. Thanks for creating it :)

**Comment by alexfoxy** [comment]
Good idea, I'll add it to the next release :)

**Comment by alexfoxy** [comment]
Done
