### ISSUE TITLE
Add easing functions

### ISSUE THREAD

**Issue by ga-fleury** [alexfoxy/lax.js#92]
I've recently been using lax a lot for a homepage project I'm working on but I'd love to have a way to define an easing function so that I'm able to define starting and finishing points coordinates and mess around with the timing using easing

**Comment by alexfoxy** [comment]
You could try this pull request to see if it met your requirements #70. Otherwise could you add a CSS easing to the element you are animating?

**Comment by alexfoxy** [comment]
@ga-fleury Just to let you know that I have been working on a new lax 2.0 which has custom easings plus many more fun features! Check out the alpha here: https://github.com/alexfoxy/laxxx/tree/version-2

**Comment by alexfoxy** [comment]
Hey @ga-fleury just so you're aware lax 2.0 has now been released and has easing functions! Check it out :)
