### ISSUE TITLE
Feature Request: add clip-path attribute key

### ISSUE THREAD

**Issue by sharanda** [alexfoxy/lax.js#93]
Clip-path attribute would allow to create nice 'crop' and opening effects;

The attribute has wide support across web-browsers: https://caniuse.com/#search=clip-path (might need to add -webkit- prefix for Safari)

Performs well in majority of web-browsers

In most cases clip-path might replace need to animate width/height attributes;

Please consider, cheers.

**Comment by alexfoxy** [comment]
Hey @sharanda 

I've been working on a 2.0 update which allows you to specify a custom css animation. Check out the alpha here: https://github.com/alexfoxy/laxxx/tree/version-2

The code would look something like:

```
 lax.addElements(".my-element", {
        scrollY: {
          "clip-path": [
            [0, 100],
            [0, 100],
            {
              cssFn: (val) => {
                return `clip-path: circle(${val}%)`
              }
            }
          ],
        }
```

**Comment by alexfoxy** [comment]
Hey @sharanda. Lax 2.0 is now available and you should be able to achieve a clip-path effect with the cssFn feature.
