### ISSUE TITLE
Anchor for horizontal scroll

### ISSUE THREAD

**Issue by bragovo** [alexfoxy/lax.js#95]
I use `lax.update(window.scrollX)` for horizontal scroll from here https://github.com/alexfoxy/laxxx/issues/28 and it's works fine, but anchor `o.anchorTop = Math.floor(rect.top) + window.scrollY` use `scrollY` - is it possible to add option for horizontal scroll?

**Comment by alexfoxy** [comment]
Can you just use lax.update(window.scrollY) ?

**Comment by bragovo** [comment]
Unfortunately not. It's because page design like this https://pianotriofest.com/ or https://canals-amsterdam.nl/
Exactly global horizontal layout, yes, it's specific task but I need it.

**Comment by alexfoxy** [comment]
Ah I See. You want to animate something for both scroll directions. How about,

```
	const updateLax = () => {
		lax.update(window.scrollY + window.scrollX) 
		window.requestAnimationFrame(updateLax)
	}

	window.requestAnimationFrame(updateLax)
```

Also there is a version 2.0 currently in alpha which might be of interest for you:
https://github.com/alexfoxy/laxxx/tree/version-2

**Comment by bragovo** [comment]
Sorry, seems I can't explain problem, my bad.  When I use `lax.update(window.scrollX)` animation works fine if I use `scrollPos` like:
```
      <figure
        ref={ImgRef}
        data-lax-opacity="0 0, 200 1"
      >
```
It's starts from left and stop on 200px, but when I use anchor, like:
```
      <figure
        ref={ImgRef}
        data-lax-opacity="0 0, 200 1"
        data-lax-anchor="self"
      >
```
Animations on all elements starts at same time and immediately. It's because anchor animations count `getBoundingClientRect().top`, but in my case it must be `getBoundingClientRect().left`. In horizontal layout all elements position at the top on Y-axis.

**Comment by alexfoxy** [comment]
Hmm okay. Let me know if you need any help with 2.0, the docs are a bit sparse but check out the examples. Happy to work in anything you need to 2.0 :)

**Comment by bragovo** [comment]
Look at this commit: https://github.com/luckypike/laxxx/commit/f27bc407d564c7fe6b27c62ce32271db255d46e9
I added `data-lax-anchor-axis` for element, after this everything works fine.

But I'll check 2.0 version, maybe there is no problem there.

**Comment by bragovo** [comment]
Yeah, thanks, looks like 2.0 works fine!
