### ISSUE TITLE
Preset demo page

### ISSUE THREAD

**Issue by Zmove** [alexfoxy/lax.js#96]
Hello,

I really like that library, congratulation to the author.

I wonder if it would be possible to create a page with a demo of all lax presets, it would be make our life easier to choose a preset + we could test if all things works as expected by comparing what we have with the effect we should have.

Thank you, and continue your great work, the alpha version features seems awesome !

Best regards,

**Comment by alexfoxy** [comment]
Yes this would be a good addition. I’ll get one together for the 2.0
release.

**Comment by alexfoxy** [comment]
Hey @Zmove, Lax 2.0 is now available with a new preset explorer. Check it out: https://alexfox.dev/lax.js/preset-explorer
