### ISSUE TITLE
Feature Request: get response time? (detect poor performance)

### ISSUE THREAD

**Issue by sharanda** [alexfoxy/lax.js#97]
We all know that laxxx is very light and efficient. However, I've faced an issue when a customer's device is incapable to animate an effect properly (or even crash). It might happen on: entry-level devices, under battery-saving mode, or if a user is having a video call on the background.

Is it possible to receive a browser's response time to provide a fallback option? Or any other way to detect poor performance?

Thanks.

**Comment by alexfoxy** [comment]
Hey,

I would suggest measuring the render frame duration using
requestAnimationFrame and then disable animations if the frame rate drops
below a certain threshold

There are some ideas here:
https://stackoverflow.com/questions/28729514/detect-browser-graphics-performance
