### ISSUE TITLE
Missmatching order of scale and translateX in the same transform

### ISSUE THREAD

**Issue by mrstalon** [alexfoxy/lax.js#98]
I am using a lot animations that combines both scale and translateX styles and came up with an issue. Since `transform: translateX(val) scale(val)` and `transform: scale(val) translateX(val)` will lead to different UI output it is very important that `lax.js ` applies styles in the same order as in code. I've got `data-lax-translate-x` and `data-lax-scale` ( in this order ) works as expected at Chrome and Safari. But at the Edge the order is different - firstly comes scale, than traslate.

Can we trust the order of styles lax.js is applying or it **depends**? And if it is, I think this is an issue needed to be solved

**Comment by alexfoxy** [comment]
Interesting bug! Do you think you could possibly check if this problem exists when using the new 2.0 version of lax? Beta available here: https://github.com/alexfoxy/lax.js/tree/version-2

**Comment by mrstalon** [comment]
@alexfoxy Sure, but only if 2.0 version is published on yarn. Is it?

**Comment by alexfoxy** [comment]
Hey, following the release of Lax 2.0 I am now closing this issue.
