### ISSUE TITLE
Is there a possibility to scroll with JS

### ISSUE THREAD

**Issue by mrstalon** [alexfoxy/lax.js#99]
I've came up with an issue trying to use `window.scrollTo(0, anyNumber)`. Firstly scroll goes to defined position, but than returns back to the initial state. Seems like update function with `requestAnimationFrame` takes all the control of scroll and do not allow anything to control its state

```javascript
const updateLax = () => {
          lax.update(window.scrollY);
          window.requestAnimationFrame(updateLax);
     };

window.requestAnimationFrame(updateLax);
```

**Comment by alexfoxy** [comment]
Lax does not control the window scroll position, just reads the value. If you can create an example in codepen or something I’ll take a look.

**Comment by mrstalon** [comment]
@afanjul Yeap, after your reply and a couple more hours of investigation I understand that issue isn't related to lax
Thank you for quick feedback
